### ISSUE TITLE
What should be in config.json ?

### ISSUE THREAD

**Issue by Djailla** [flopp/activities#1]
Hello Florian, I'm interested by your dev and could give a hand :)

What should I add in config.json to make it work ?

**Comment by flopp** [comment]
Thanks for your interest ;)

This is very much work-in-progress and highly experimental. I need to clean-up the code and add some documentation on how to use it.

`config.json` contains the `client_id` and the `client_secret` of your Strava app (you can get these values from https://www.strava.com/settings/api), e.g.

```
{
    "client_id": "12345",
    "client_secret": "some hex string"
}
```

`account.json` contains `refresh_token`, `access_token`, `expires_at` from an authenticated Strava user.

**Comment by Djailla** [comment]
I manage to make it work and even push a PR :p
