### ISSUE TITLE
auth error

### ISSUE THREAD

**Issue by yihong0618** [flopp/activities#25]
Hi~
I just get strava client id and client secret
but when I execute the command `.env/bin/activities     --auth`
I got error in the browser
jinja2.exceptions.TemplateNotFound
jinja2.exceptions.TemplateNotFound: main.html
png like this maybe I missed something?
![image](https://user-images.githubusercontent.com/15976103/86333395-67b46c00-bc7e-11ea-9ef1-1e5390e5bbe2.png)

**Comment by Djailla** [comment]
@yihong0618 can you try again ?

**Comment by yihong0618** [comment]
@Djailla Still the problem on my mac 
jinja2.exceptions.TemplateNotFound
jinja2.exceptions.TemplateNotFound: main.html

**Comment by Djailla** [comment]
@yihong0618 I did retry from scratch and no issue.

Can you try to delete `.env` folder and run again the steps ?

**Comment by yihong0618** [comment]
@Djailla @flopp delete .env worked. Thank you very much. Its very cool and vert fast, thank you for your wonderful work!!!
![image](https://user-images.githubusercontent.com/15976103/86446590-bd544b80-bd46-11ea-9687-7041db548061.png)
