### ISSUE TITLE
Display statistics about the filtered activities

### ISSUE THREAD

**Issue by flopp** [flopp/activities#32]
Currently, the filter page only displays the number of matching activities.
Add some more statistics about the matching activities, e.g.

- Total, max, average distance
- Total, max, average elevation gain
- Total, max, average moving time
...

**Comment by yihong0618** [comment]
Can you add heatmap like strava's heatmap? Like this https://www.strava.com/athletes/58330365/heatmaps/59776a20#13/38.86537/121.51978
