### ISSUE TITLE
Can we add pace or heartrate for activites?

### ISSUE THREAD

**Issue by yihong0618** [flopp/activities#42]
I think strava api offer this attr, or maybe we can let user config the attrs in config.js?

**Comment by flopp** [comment]
Pace and heartreate are available from the Strava API as `average_speed`and `average_heartrate`, so we could add this quite easily. I have to check what's the best way to extend the Sqlite DB...

**Comment by Djailla** [comment]
There is a JS library to parse strava data :

https://github.com/sports-alliance/sports-lib

We could only store in DB the file

**Comment by yihong0618** [comment]
Cool, thanks. @flopp
