### ISSUE TITLE
ERROR: Failed building wheel for pycairo

### ISSUE THREAD

**Issue by SimonHaas** [flopp/activities#49]
Following your README.md I ran 

git clone https://github.com/flopp/activities.git
cd activities
python3 -m venv .env
.env/bin/pip install --upgrade pip
.env/bin/pip install .

on a Ubuntu 21.04 container on proxmox as well as WSL Ubuntu, which resulted in the following error

Processing /root/activities
  Preparing metadata (setup.py) ... done
Collecting click
  Using cached click-8.0.3-py3-none-any.whl (97 kB)
Collecting flask
  Using cached Flask-2.0.2-py3-none-any.whl (95 kB)
Collecting geopy
  Using cached geopy-2.2.0-py3-none-any.whl (118 kB)
Collecting polyline
  Using cached polyline-1.4.0-py2.py3-none-any.whl (4.4 kB)
Collecting py-staticmaps[cairo]
  Using cached py_staticmaps-0.4.0-py3-none-any.whl
Collecting sqlalchemy
  Using cached SQLAlchemy-1.4.27-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
Collecting stravalib
  Using cached stravalib-0.10.4-py3-none-any.whl
Collecting itsdangerous>=2.0
  Using cached itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Collecting Jinja2>=3.0
  Using cached Jinja2-3.0.3-py3-none-any.whl (133 kB)
Collecting Werkzeug>=2.0
  Using cached Werkzeug-2.0.2-py3-none-any.whl (288 kB)
Collecting geographiclib<2,>=1.49
  Using cached geographiclib-1.52-py3-none-any.whl (38 kB)
Collecting six>=1.8.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting requests
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting python-slugify
  Using cached python_slugify-5.0.2-py2.py3-none-any.whl (6.7 kB)
Collecting PILLOW
  Using cached Pillow-8.4.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting s2sphere
  Using cached s2sphere-0.2.5-py2.py3-none-any.whl (23 kB)
Collecting svgwrite
  Using cached svgwrite-1.4.1-py3-none-any.whl (66 kB)
Collecting pycairo
  Using cached pycairo-1.20.1.tar.gz (344 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting greenlet!=0.4.17
  Using cached greenlet-1.1.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (153 kB)
Collecting units
  Using cached units-0.7-py3-none-any.whl
Collecting pytz
  Using cached pytz-2021.3-py2.py3-none-any.whl (503 kB)
Collecting arrow
  Using cached arrow-1.2.1-py3-none-any.whl (63 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.0.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.7-py3-none-any.whl (38 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting python-dateutil>=2.7.0
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting text-unidecode>=1.3
  Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Collecting future>=0.15
  Using cached future-0.18.2-py3-none-any.whl
Using legacy 'setup.py install' for activities, since package 'wheel' is not installed.
Building wheels for collected packages: pycairo
  Building wheel for pycairo (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/activities/.env/bin/python3 /root/activities/.env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp90487_lh
       cwd: /tmp/pip-install-fasvdjhp/pycairo_0922a36a62564a85b4cd2185e1e4f6df
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/cairo
  copying cairo/__init__.py -> build/lib.linux-x86_64-3.9/cairo
  copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.9/cairo
  copying cairo/py.typed -> build/lib.linux-x86_64-3.9/cairo
  running build_ext
  'pkg-config' not found.
  Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']
  ----------------------------------------
  ERROR: Failed building wheel for pycairo
Failed to build pycairo
ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects

**Comment by flopp** [comment]
Thank you for the report. I've now removed preview images (and thus pystaticmaps + pycairo) - they didn't work correctly anyway...
