### ISSUE TITLE
Very cool repo.

### ISSUE THREAD

**Issue by yihong0618** [flopp/activities#5]
I think that's what we need because more and more running app close their websites, as https://www.nike.com/nrc-app and https://www.runtastic.com/en/web-update
Thank you very much.

**Comment by flopp** [comment]
Thanks! I'm happy that you find this project useful.

**Comment by yihong0618** [comment]
@flopp 
Hi~
A lot thanks for your project. And I use most of your code for GitHub Action which generate static website daily and I wrote a `React` version  you can see here https://yihong.run/running and the [repo](https://github.com/yihong0618/blog)

---
Thank you again for your repo which helped me achieve a long time idea

**Comment by Djailla** [comment]
Splendid !

I will learn react now !

Could you add a manual so that I could try it also ?

**Comment by yihong0618** [comment]
> Splendid !
> 
> I will learn react now !
> 
> Could you add a manual so that I could try it also ?

@Djailla 
Maybe you could change a little code because I use `nike run club` to run and download the activates to upload to strava then use `activities -s` to update db and js.
If you use strava to run, You can skip first two steps.I will write some manual maybe later.

**Comment by flopp** [comment]
@yihong0618 that's really cool!

**Comment by yihong0618** [comment]
> Splendid !
> 
> I will learn react now !
> 
> Could you add a manual so that I could try it also ?

@Djailla sorry for late.
I exact the running page, and add strava, runtastic, nike run club support.

repo and English manual https://github.com/yihong0618/running_page/blob/master/README-EN.md
I use `deepL` translate sorry for that.
